"""Household taxonomy for homeowner document classification.

A comprehensive taxonomy covering typical household document categories
including financial, property, medical, legal, and personal documents.
"""

from typing import ClassVar

from drover.taxonomy.base import BaseTaxonomy


class HouseholdTaxonomy(BaseTaxonomy):
    """Default taxonomy for household/homeowner documents."""

    CANONICAL_DOMAINS: ClassVar[set[str]] = {
        "career",
        "education",
        "financial",
        "food",
        "government",
        "household",
        "housing",
        "insurance",
        "legal",
        "lifestyle",
        "medical",
        "personal",
        "pets",
        "property",
        "reference",
        "utilities",
    }

    CANONICAL_CATEGORIES: ClassVar[dict[str, set[str]]] = {
        "financial": {
            "banking",
            "credit",
            "investment",
            "loan",
            "payment",
            "reference",
            "retirement",
            "tax",
        },
        "property": {
            "expense",
            "hoa",
            "improvement",
            "maintenance",
            "mortgage",
            "payment",
            "reference",
            "rental",
            "search",
        },
        "medical": {
            "claim",
            "expense",
            "immunization",
            "lab_result",
            "mental_health",
            "payment",
            "prescription",
            "primary_care",
            "reference",
            "specialist",
            "vision",
        },
        "legal": {
            "contract",
            "correspondence",
            "court",
            "estate",
            "reference",
        },
        "education": {
            "certification",
            "correspondence",
            "expense",
            "financial_aid",
            "payment",
            "reference",
            "transcript",
        },
        "insurance": {
            "auto",
            "claim",
            "health",
            "home",
            "life",
            "payment",
            "reference",
            "umbrella",
        },
        "personal": {
            "correspondence",
            "expense",
            "identity",
            "membership",
            "reference",
            "travel",
        },
        "government": {
            "correspondence",
            "federal",
            "local",
            "reference",
            "state",
        },
        "utilities": {
            "correspondence",
            "electric",
            "expense",
            "gas",
            "internet",
            "payment",
            "phone",
            "reference",
            "trash",
            "water",
        },
        "career": {
            "application",
            "benefit",
            "client",
            "compensation",
            "consulting",
            "correspondence",
            "documentation",
            "employer",
            "expense",
            "job_search",
            "leadership",
            "meeting",
            "presentation",
            "reference",
            "review",
            "training",
        },
        "food": {
            "meal_plan",
            "recipe",
            "reference",
        },
        "household": {
            "documentation",
            "expense",
            "goods",
            "network",
            "insurance",
            "loans",
            "maintenance",
            "purchase",
            "reference",
            "registration",
            "vehicle",
        },
        "lifestyle": {
            "expense",
            "goal",
            "interest",
            "planning",
            "reference",
            "travel",
            "volunteering",
        },
        "pets": {
            "expense",
            "medical",
            "reference",
            "registration",
        },
        "reference": {
            "documentation",
            "topic",
        },
        "housing": {
            "payment",
            "property",
            "reference",
            "rental",
            "reservation",
            "search",
        },
    }

    CANONICAL_DOCTYPES: ClassVar[set[str]] = {
        "agreement",
        "application",
        "bill",
        "certificate",
        "confirmation",
        "contract",
        "deed",
        "estimate",
        "form",
        "guide",
        "identification",
        "invoice",
        "itinerary",
        "journal",
        "lease",
        "letter",
        "license",
        "listing",
        "manual",
        "notice",
        "offer",
        "passport",
        "paystub",
        "permit",
        "plan",
        "policy",
        "portfolio",
        "presentation",
        "quote",
        "receipt",
        "recipe",
        "record",
        "reference",
        "referral",
        "report",
        "reservation",
        "resume",
        "return",
        "statement",
        "title",
        "trust",
        "warranty",
        "will",
    }

    DOMAIN_ALIASES: ClassVar[dict[str, str]] = {
        "apartment": "housing",
        "attorney": "legal",
        "auto": "household",
        "automobile": "household",
        "banking": "financial",
        "bills": "utilities",
        "car": "household",
        "college": "education",
        "doctor": "medical",
        "federal": "government",
        "finance": "financial",
        "finances": "financial",
        "gov": "government",
        "govt": "government",
        "health": "medical",
        "healthcare": "medical",
        "home": "property",
        "hospital": "medical",
        "house": "property",
        "job": "career",
        "law": "legal",
        "lawyer": "legal",
        "lease": "housing",
        "money": "financial",
        "real_estate": "housing",
        "realestate": "housing",
        "rental": "housing",
        "rentals": "housing",
        "school": "education",
        "state": "government",
        "travel": "lifestyle",
        "truck": "household",
        "university": "education",
        "vehicle": "household",
        "vehicles": "household",
        "work": "career",
        "non_profit": "personal",
        "nonprofit": "personal",
    }

    CATEGORY_ALIASES: ClassVar[dict[tuple[str, str], str]] = {
        ("career", "interviewing"): "job_search",
        ("career", "docs"): "documentation",
        # Hierarchy rule: artifact-form terms (resume, manual, agreement, ...)
        # are doctype-only. These aliases redirect LLM-emitted forms to the
        # appropriate subject category in each domain. Domains without an
        # entry below deliberately surface the term as drift (canonical: null)
        # for ground-truth refinement.
        ("career", "resume"): "job_search",
        ("reference", "manual"): "documentation",
        ("property", "agreement"): "mortgage",
        ("housing", "agreement"): "rental",
        ("personal", "goals"): "identity",
        ("financial", "bank"): "banking",
        ("financial", "checking"): "banking",
        ("financial", "savings"): "banking",
        ("financial", "credit_card"): "credit",
        ("financial", "credit_cards"): "credit",
        ("financial", "cards"): "credit",
        ("financial", "stocks"): "investment",
        ("financial", "bonds"): "investment",
        ("financial", "brokerage"): "investment",
        ("financial", "equities"): "investment",
        ("financial", "401k"): "retirement",
        ("financial", "ira"): "retirement",
        ("financial", "pension"): "retirement",
        ("financial", "taxes"): "tax",
        ("financial", "irs"): "tax",
        ("financial", "account"): "banking",
        ("financial", "account_information"): "banking",
        ("financial", "account_statement"): "banking",
        ("financial", "accounting"): "banking",
        ("financial", "statement"): "banking",
        ("financial", "transaction"): "banking",
        ("financial", "transfer"): "banking",
        ("financial", "transfer_money"): "banking",
        ("financial", "credit_card_statement"): "credit",
        ("financial", "distribution"): "retirement",
        ("financial", "loan_documents"): "loan",
        ("financial", "payment_services"): "payment",
        # property domain
        ("property", "home_improvement"): "improvement",
        ("property", "home_improvements"): "improvement",
        ("property", "repairs"): "maintenance",
        ("property", "home_repairs"): "maintenance",
        ("property", "association"): "hoa",
        ("property", "condo"): "hoa",
        ("property", "lease"): "rental",
        ("property", "housing"): "rental",
        ("property", "termination_of_service"): "maintenance",
        ("property", "receipts"): "expense",
        ("property", "purchases"): "expense",
        ("property", "spending"): "expense",
        # medical domain
        ("medical", "bills"): "expense",
        ("medical", "claims"): "claim",
        ("medical", "rx"): "prescription",
        ("medical", "medications"): "prescription",
        ("medical", "labs"): "lab_result",
        ("medical", "tests"): "lab_result",
        ("medical", "annual_examination"): "primary_care",
        ("medical", "exam"): "primary_care",
        ("medical", "visit"): "primary_care",
        ("medical", "behavior_modification"): "mental_health",
        # insurance domain
        ("insurance", "car"): "auto",
        ("insurance", "vehicle"): "auto",
        ("insurance", "homeowners"): "home",
        ("insurance", "property"): "home",
        ("insurance", "medical"): "health",
        # housing domain
        ("housing", "apartment"): "rental",
        ("housing", "lease"): "rental",
        ("housing", "real_estate"): "property",
        ("housing", "mortgage"): "property",
        ("housing", "home"): "property",
        # lifestyle domain
        ("lifestyle", "trip"): "travel",
        ("lifestyle", "vacation"): "travel",
        ("lifestyle", "trips"): "travel",
        ("lifestyle", "trip_itinerary"): "travel",
        ("lifestyle", "travel_planning"): "planning",
        ("lifestyle", "receipts"): "expense",
        ("lifestyle", "purchases"): "expense",
        ("lifestyle", "spending"): "expense",
        # pets domain
        ("pets", "receipts"): "expense",
        ("pets", "purchases"): "expense",
        ("pets", "spending"): "expense",
        # household domain
        ("household", "receipts"): "expense",
        ("household", "purchases"): "expense",
        ("household", "spending"): "expense",
        ("household", "vehicle_registration_renewal"): "registration",
        ("household", "vehicle_related_policies"): "insurance",
        # career domain
        ("career", "receipts"): "expense",
        ("career", "purchases"): "expense",
        ("career", "spending"): "expense",
        ("career", "billing"): "compensation",
        # financial domain - additional aliases
        ("financial", "billing"): "payment",
        ("financial", "compensation"): "payment",
        ("financial", "correspondence"): "banking",
        # lifestyle domain - career-related aliases
        ("lifestyle", "career"): "planning",
        ("lifestyle", "job_search"): "planning",
        ("lifestyle", "training"): "interest",
        ("lifestyle", "volunteer_programming"): "volunteering",
        # personal domain - non-profit aliases (when non_profit maps to personal)
        ("personal", "annual_report"): "membership",
        # household domain - vehicles aliases (when vehicles maps to household)
        ("household", "vehicle_service_records"): "vehicle",
        # education domain
        ("education", "receipts"): "expense",
        ("education", "purchases"): "expense",
        ("education", "spending"): "expense",
        ("education", "tuition"): "expense",
        # singular `purchase` (LLM emits singular alongside plural)
        ("food", "purchase"): "expense",
        ("property", "purchase"): "expense",
        ("personal", "purchase"): "expense",
        ("lifestyle", "purchase"): "expense",
        ("career", "purchase"): "expense",
        # `documentation` is the LLM's synonym for `reference` materials
        ("utilities", "documentation"): "reference",
        ("personal", "documentation"): "reference",
        ("property", "documentation"): "reference",
        ("insurance", "documentation"): "reference",
        # gerund variants of `travel`
        ("personal", "traveling"): "travel",
        ("lifestyle", "traveling"): "travel",
        # `billing` is what the LLM calls a payment notice
        ("insurance", "billing"): "payment",
        ("medical", "billing"): "payment",
        # one-off but unambiguous
        ("lifestyle", "gift_giving"): "expense",
    }

    DOCTYPE_ALIASES: ClassVar[dict[str, str]] = {
        "bank_statement": "statement",
        "account_statement": "statement",
        "monthly_statement": "statement",
        "bill": "invoice",
        "payment": "receipt",
        "purchase": "receipt",
        "transaction": "receipt",
        "service_agreement": "agreement",
        "correspondence": "letter",
        "mail": "letter",
        "notification": "notice",
        "alert": "notice",
        "reminder": "notice",
        "document": "form",
        "paperwork": "form",
        "insurance_policy": "policy",
        "coverage": "policy",
        "cert": "certificate",
        "certification": "certificate",
        "credential": "certificate",
        "assessment": "report",
        "summary": "report",
        "analysis": "report",
        "history": "record",
        "log": "record",
        "proposal": "estimate",
        "bid": "quote",
        "owner_manual": "manual",
        "instructions": "guide",
        "how_to": "guide",
        "1040": "return",
        "w2": "form",
        "w-2": "form",
        "1099": "form",
        "property_deed": "deed",
        "car_title": "title",
        "vehicle_title": "title",
        "drivers_license": "license",
        "registration": "license",
        "cookbook": "recipe",
        "cv": "resume",
        "shot_record": "record",
        "travel_plan": "itinerary",
        # paystub aliases
        "pay_stub": "paystub",
        "paycheck": "paystub",
        "earnings_statement": "paystub",
        # lease aliases
        "rental_agreement": "lease",
        "apartment_lease": "lease",
        "rental_lease": "lease",
        # listing aliases
        "property_listing": "listing",
        "mls_listing": "listing",
        "real_estate_listing": "listing",
        # offer aliases
        "purchase_offer": "offer",
        "real_estate_offer": "offer",
        # closing aliases
        "closing_docs": "statement",
        "settlement_statement": "statement",
        "hud1": "statement",
        # hoa aliases
        "hoa_dues": "statement",
        "hoa_bill": "statement",
        # discovered aliases
        "billing_statement": "statement",
        "claim_confirmation": "confirmation",
        "insurance": "policy",
        "lease_agreement": "lease",
        "mortgage": "agreement",
        "pay_bill": "receipt",
        "payment_confirmation": "confirmation",
        "payment_receipt": "receipt",
        "payment_scheduled": "confirmation",
        "request_for_termination_of_service": "notice",
        "transfer_money_confirmation": "confirmation",
        # discovered aliases - job search and reference
        "article": "reference",
        "call_notes": "record",
        "job_listing": "listing",
        "job_posting": "listing",
        # discovered aliases - healthcare
        "list": "reference",
        "medical_billing_statement": "statement",
        "patient_care_summary": "report",
        # discovered aliases - lifestyle
        "discharge_summary": "report",
        "service_record": "record",
        "webpage": "reference",
    }

    @property
    def name(self) -> str:
        """Unique identifier for this taxonomy."""
        return "household"
