"""Household taxonomy for homeowner document classification.

A comprehensive taxonomy covering typical household document categories
including financial, property, medical, legal, and personal documents.
"""

from typing import ClassVar

from drover.taxonomy.base import BaseTaxonomy


class HouseholdTaxonomy(BaseTaxonomy):
    """Default taxonomy for household/homeowner documents."""

    CANONICAL_DOMAINS: ClassVar[set[str]] = {
        "financial",
        "property",
        "medical",
        "legal",
        "employment",
        "education",
        "insurance",
        "vehicles",
        "personal",
        "utilities",
        "career",
        "food",
        "household",
        "government",
        "lifestyle",
        "pets",
        "reference",
        "housing",
        "other",
    }

    CANONICAL_CATEGORIES: ClassVar[dict[str, set[str]]] = {
        "financial": {
            "banking",
            "credit",
            "investments",
            "retirement",
            "taxes",
            "loans",
            "receipts",
            "statements",
            "other",
        },
        "property": {
            "mortgage",
            "maintenance",
            "improvements",
            "hoa",
            "rental",
            "properties",
            "rentals",
            "search",
            "reference",
            "other",
        },
        "medical": {
            "records",
            "billing",
            "insurance_claims",
            "prescriptions",
            "lab_results",
            "dental",
            "mental_health",
            "primary_care",
            "specialists",
            "vision",
            "immunizations",
            "reference",
            "other",
        },
        "legal": {
            "contracts",
            "estate_planning",
            "court",
            "correspondence",
            "identification",
            "reference",
            "other",
        },
        "employment": {
            "compensation",
            "benefits",
            "performance",
            "correspondence",
            "other",
        },
        "education": {
            "transcripts",
            "certifications",
            "correspondence",
            "financial_aid",
            "other",
        },
        "insurance": {
            "auto",
            "home",
            "life",
            "health",
            "umbrella",
            "claims",
            "other",
        },
        "vehicles": {
            "purchase",
            "registration",
            "maintenance",
            "insurance",
            "loans",
            "reference",
            "other",
        },
        "personal": {
            "identity",
            "correspondence",
            "memberships",
            "travel",
            "other",
        },
        "government": {
            "federal",
            "state",
            "local",
            "correspondence",
            "other",
        },
        "utilities": {
            "electric",
            "gas",
            "water",
            "internet",
            "phone",
            "trash",
            "other",
        },
        "career": {
            "applications",
            "clients",
            "consulting",
            "documentation",
            "employers",
            "interviewing",
            "job_search",
            "leadership",
            "meetings",
            "performance_reviews",
            "presentations",
            "professional_development",
            "reference",
            "resumes",
            "other",
        },
        "food": {
            "meal_plans",
            "recipes",
            "reference",
            "other",
        },
        "household": {
            "emergency_preparedness",
            "home_network",
            "maintenance",
            "vehicles",
            "other",
        },
        "lifestyle": {
            "goals",
            "interests",
            "planning",
            "travel",
            "trips",
            "volunteering",
            "other",
        },
        "pets": {
            "medical",
            "registration",
            "other",
        },
        "reference": {
            "manuals",
            "topics",
            "other",
        },
        "housing": {
            "properties",
            "reference",
            "rentals",
            "search",
            "other",
        },
        "other": {
            "uncategorized",
        },
    }

    CANONICAL_DOCTYPES: ClassVar[set[str]] = {
        "statement",
        "invoice",
        "receipt",
        "contract",
        "agreement",
        "letter",
        "notice",
        "form",
        "application",
        "policy",
        "certificate",
        "report",
        "record",
        "bill",
        "estimate",
        "quote",
        "warranty",
        "manual",
        "guide",
        "tax_return",
        "tax_form",
        "deed",
        "title",
        "license",
        "permit",
        "recipe",
        "meal_plan",
        "resume",
        "cover_letter",
        "portfolio",
        "presentation",
        "reference_letter",
        "immunization_record",
        "referral",
        "inspection_report",
        "will",
        "trust",
        "power_of_attorney",
        "passport",
        "birth_certificate",
        "social_security_card",
        "itinerary",
        "booking_confirmation",
        "journal",
        "vaccination_record",
        "adoption_papers",
        "id_card",
        "paystub",
        "lease",
        "listing",
        "offer",
        "closing_statement",
        "hoa_statement",
        "other",
    }

    DOMAIN_ALIASES: ClassVar[dict[str, str]] = {
        "finances": "financial",
        "finance": "financial",
        "money": "financial",
        "banking": "financial",
        "home": "property",
        "house": "property",
        "health": "medical",
        "healthcare": "medical",
        "doctor": "medical",
        "hospital": "medical",
        "law": "legal",
        "attorney": "legal",
        "lawyer": "legal",
        "work": "employment",
        "job": "employment",
        "school": "education",
        "college": "education",
        "university": "education",
        "car": "vehicles",
        "auto": "vehicles",
        "automobile": "vehicles",
        "truck": "vehicles",
        "gov": "government",
        "govt": "government",
        "federal": "government",
        "state": "government",
        "bills": "utilities",
        # housing domain aliases
        "real_estate": "housing",
        "realestate": "housing",
        "rental": "housing",
        "rentals": "housing",
        "apartment": "housing",
        "lease": "housing",
        # other
        "misc": "other",
        "miscellaneous": "other",
        "unknown": "other",
    }

    CATEGORY_ALIASES: ClassVar[dict[tuple[str, str], str]] = {
        ("employment", "resumes"): "resumes",
        ("employment", "interviewing"): "interviewing",
        ("personal", "travel"): "travel",
        ("personal", "goals"): "goals",
        ("financial", "bank"): "banking",
        ("financial", "checking"): "banking",
        ("financial", "savings"): "banking",
        ("financial", "credit_card"): "credit",
        ("financial", "credit_cards"): "credit",
        ("financial", "cards"): "credit",
        ("financial", "stocks"): "investments",
        ("financial", "bonds"): "investments",
        ("financial", "brokerage"): "investments",
        ("financial", "equities"): "investments",
        ("financial", "401k"): "retirement",
        ("financial", "ira"): "retirement",
        ("financial", "pension"): "retirement",
        ("financial", "tax"): "taxes",
        ("financial", "irs"): "taxes",
        ("property", "home_improvement"): "improvements",
        ("property", "home_improvements"): "improvements",
        ("property", "repairs"): "maintenance",
        ("property", "home_repairs"): "maintenance",
        ("property", "association"): "hoa",
        ("property", "condo"): "hoa",
        ("medical", "health_records"): "records",
        ("medical", "medical_records"): "records",
        ("medical", "bills"): "billing",
        ("medical", "claims"): "insurance_claims",
        ("medical", "rx"): "prescriptions",
        ("medical", "medications"): "prescriptions",
        ("medical", "labs"): "lab_results",
        ("medical", "tests"): "lab_results",
        ("insurance", "car"): "auto",
        ("insurance", "vehicle"): "auto",
        ("insurance", "homeowners"): "home",
        ("insurance", "property"): "home",
        ("insurance", "medical"): "health",
        # housing domain
        ("housing", "apartment"): "rentals",
        ("housing", "lease"): "rentals",
        ("housing", "real_estate"): "properties",
        ("housing", "mortgage"): "properties",
        ("housing", "home"): "properties",
        # career domain
        ("career", "client"): "clients",
        ("career", "meeting"): "meetings",
        ("career", "docs"): "documentation",
        # lifestyle domain
        ("lifestyle", "trip"): "trips",
        ("lifestyle", "vacation"): "trips",
        ("lifestyle", "travel_planning"): "planning",
    }

    DOCTYPE_ALIASES: ClassVar[dict[str, str]] = {
        "bank_statement": "statement",
        "account_statement": "statement",
        "monthly_statement": "statement",
        "bill": "invoice",
        "payment": "receipt",
        "purchase": "receipt",
        "transaction": "receipt",
        "service_agreement": "agreement",
        "correspondence": "letter",
        "mail": "letter",
        "notification": "notice",
        "alert": "notice",
        "reminder": "notice",
        "document": "form",
        "paperwork": "form",
        "insurance_policy": "policy",
        "coverage": "policy",
        "cert": "certificate",
        "certification": "certificate",
        "credential": "certificate",
        "assessment": "report",
        "summary": "report",
        "analysis": "report",
        "history": "record",
        "log": "record",
        "proposal": "estimate",
        "bid": "quote",
        "owner_manual": "manual",
        "instructions": "guide",
        "how_to": "guide",
        "1040": "tax_return",
        "w2": "tax_form",
        "w-2": "tax_form",
        "1099": "tax_form",
        "property_deed": "deed",
        "car_title": "title",
        "vehicle_title": "title",
        "drivers_license": "license",
        "registration": "license",
        "cookbook": "recipe",
        "cv": "resume",
        "shot_record": "immunization_record",
        "travel_plan": "itinerary",
        # paystub aliases
        "pay_stub": "paystub",
        "paycheck": "paystub",
        "earnings_statement": "paystub",
        # lease aliases
        "rental_agreement": "lease",
        "apartment_lease": "lease",
        "rental_lease": "lease",
        # listing aliases
        "property_listing": "listing",
        "mls_listing": "listing",
        "real_estate_listing": "listing",
        # offer aliases
        "purchase_offer": "offer",
        "real_estate_offer": "offer",
        # closing aliases
        "closing_docs": "closing_statement",
        "settlement_statement": "closing_statement",
        "hud1": "closing_statement",
        # hoa aliases
        "hoa_dues": "hoa_statement",
        "hoa_bill": "hoa_statement",
        "unknown": "other",
    }

    @property
    def name(self) -> str:
        """Unique identifier for this taxonomy."""
        return "household"
