"""Format-coverage matrix reporter for the Docling evaluation spike.

Builds one fixture per supported extension, runs both loaders against
each, and writes a markdown table to stdout (and `eval/format_matrix.md`
when --write is passed).

Status legend:
  PASS    — both loaders produced non-empty content.
  FAIL    — neither loader produced non-empty content (no regression).
  REGRESS — unstructured produced content; docling did not. Blocks
            the go decision per spike P0-6.
  GAIN    — docling produced content; unstructured did not.
  SKIP    — fixture builder cannot synthesize this extension without
            a Microsoft Office toolchain (`.doc`, `.xls`, `.ppt`).

Usage:
    uv run python scripts/build_format_matrix.py
    uv run python scripts/build_format_matrix.py --write
"""

from __future__ import annotations

import argparse
import asyncio
import sys
import tempfile
from pathlib import Path

# Allow running as a standalone script.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tests.fixtures.format_matrix.builders import (
    EXT_BUILDERS,
    UNSUPPORTED_BY_BUILDER,
    build_all,
)

from drover.loader import (
    _SUPPORTED_EXTENSIONS,
    DoclingLoader,
    DocumentLoader,
    DocumentLoadError,
)


async def _try(loader: DocumentLoader | DoclingLoader, path: Path) -> bool:
    try:
        loaded = await loader.load(path)
    except DocumentLoadError:
        return False
    return bool(loaded.content.strip())


def _status(unstructured_ok: bool, docling_ok: bool) -> str:
    if unstructured_ok and docling_ok:
        return "PASS"
    if unstructured_ok and not docling_ok:
        return "REGRESS"
    if not unstructured_ok and docling_ok:
        return "GAIN"
    return "FAIL"


def render(rows: list[tuple[str, str, str, str]]) -> str:
    lines = [
        "| Extension | Unstructured | Docling | Status |",
        "|-----------|--------------|---------|--------|",
    ]
    for ext, u, d, status in rows:
        lines.append(f"| `{ext}` | {u} | {d} | **{status}** |")
    return "\n".join(lines)


async def run() -> list[tuple[str, str, str, str]]:
    with tempfile.TemporaryDirectory() as tmp:
        paths = build_all(Path(tmp))
        rows: list[tuple[str, str, str, str]] = []
        for ext in sorted(_SUPPORTED_EXTENSIONS):
            if ext in UNSUPPORTED_BY_BUILDER:
                rows.append((ext, "n/a", "n/a", "SKIP"))
                continue
            if ext not in EXT_BUILDERS:
                rows.append((ext, "n/a", "n/a", "SKIP"))
                continue

            path = paths[ext]
            u = await _try(DocumentLoader(), path)
            d = await _try(DoclingLoader(), path)
            rows.append(
                (
                    ext,
                    "ok" if u else "fail",
                    "ok" if d else "fail",
                    _status(u, d),
                )
            )
        return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write the table to eval/format_matrix.md",
    )
    args = parser.parse_args()

    rows = asyncio.run(run())
    table = render(rows)

    sys.stdout.write(table + "\n")

    if args.write:
        out_path = Path("eval/format_matrix.md")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(
            "# Drover Format Coverage Matrix\n\n"
            "Generated by `uv run python scripts/build_format_matrix.py --write`. "
            "See `tests/test_format_matrix.py` for the no-regress test.\n\n"
            + table
            + "\n"
        )

    # Exit non-zero if any REGRESS is present so CI can fail.
    return 1 if any(r[3] == "REGRESS" for r in rows) else 0


if __name__ == "__main__":
    sys.exit(main())
