"""Path builder for generating organized file paths from classification.

Constructs paths following the format:
{domain}/{category}/{doctype}/{filename}

Where filename is generated by the naming policy.
"""

import re
from pathlib import Path

from drover.models import ClassificationResult, PathConstraints, RawClassification
from drover.naming.base import BaseNamingPolicy
from drover.taxonomy.base import BaseTaxonomy


class PathConstraintError(Exception):
    """Raised when a generated path or filename violates constraints."""


class PathBuilder:
    """Builds file paths from classification results.

    Combines folder structure with naming policy to generate
    complete, policy-compliant file paths.
    """

    def __init__(
        self,
        naming_policy: BaseNamingPolicy,
        constraints: PathConstraints | None = None,
        taxonomy: BaseTaxonomy | None = None,
        emit_entity: bool = True,
        redact_entity_in_domains: list[str] | None = None,
    ) -> None:
        """Initialize path builder.

        Args:
            naming_policy: Policy for generating filenames.
            constraints: Path constraints, or None for defaults.
            taxonomy: Optional taxonomy used to map plural canonical doctypes
                to their singular instance form for filename generation.
                Folders always use the plural form; filenames use the singular.
            emit_entity: When False, the entity slot is suppressed for every
                document, reproducing the legacy 4-component filename. When
                True (default), the entity slot is included subject to
                per-domain redaction and vendor/entity dedup.
            redact_entity_in_domains: Domains whose entity slot is suppressed
                to avoid leaking personally-identifying values into filenames.
                Defaults to ``["medical"]``.
        """
        self.naming_policy = naming_policy
        self.constraints = constraints or PathConstraints()
        self.taxonomy = taxonomy
        self.emit_entity = emit_entity
        self.redact_entity_in_domains = (
            ["medical"]
            if redact_entity_in_domains is None
            else list(redact_entity_in_domains)
        )

    def build(
        self,
        classification: RawClassification,
        original_path: Path,
    ) -> ClassificationResult:
        """Build complete classification result with suggested path.

        Args:
            classification: Normalized classification from LLM.
            original_path: Original document file path.

        Returns:
            ClassificationResult with suggested path.
        """
        folder_path = self._build_folder_path(
            domain=classification.domain,
            category=classification.category,
            doctype=classification.doctype,
        )

        filename_doctype = (
            self.taxonomy.singular_form(classification.doctype)
            if self.taxonomy is not None
            else classification.doctype
        )

        entity_for_filename = self._resolve_entity(
            classification.entity, classification.domain
        )

        filename = self.naming_policy.format_filename(
            doctype=filename_doctype,
            vendor=classification.vendor,
            subject=classification.subject,
            date=classification.date,
            extension=original_path.suffix,
            entity=entity_for_filename,
        )

        is_valid, error_message = self.naming_policy.validate_filename(filename)
        if not is_valid:
            raise PathConstraintError(
                error_message or "Generated filename violates naming constraints"
            )

        suggested_path = f"{folder_path}/{filename}"
        self._validate_path(suggested_path)

        return ClassificationResult(
            original=original_path.name,
            suggested_path=suggested_path,
            suggested_filename=filename,
            domain=classification.domain,
            category=classification.category,
            doctype=classification.doctype,
            vendor=classification.vendor,
            date=classification.date,
            subject=classification.subject,
            entity=classification.entity,
        )

    def _resolve_entity(self, entity: str, domain: str) -> str:
        """Apply emit-entity and per-domain redaction policy.

        Returns the entity value to pass to the naming policy. The
        result is empty when entity emission is disabled globally or
        when ``domain`` is in the redact list. The naming policy is
        responsible for the vendor/entity dedup; this method only
        enforces config-level suppression.
        """
        if not self.emit_entity:
            return ""
        if domain and domain.lower() in {
            d.lower() for d in self.redact_entity_in_domains
        }:
            return ""
        return entity or ""

    def _build_folder_path(
        self,
        domain: str,
        category: str,
        doctype: str,
    ) -> str:
        """Build folder path from classification components.

        Args:
            domain: Canonical domain.
            category: Canonical category.
            doctype: Canonical document type.

        Returns:
            Folder path string (without trailing slash).
        """
        parts = [domain, category, doctype]

        if len(parts) > self.constraints.max_folder_depth:
            parts = parts[: self.constraints.max_folder_depth]

        return "/".join(parts)

    def _validate_path(self, path: str) -> None:
        """Validate path against constraints.

        Args:
            path: Full suggested path.

        Raises:
            PathConstraintError: If path violates constraints.
        """
        if len(path) > self.constraints.max_path_length:
            raise PathConstraintError(
                f"Generated path exceeds max length of {self.constraints.max_path_length}: "
                f"{len(path)} chars"
            )

        folder_part, _, _ = path.rpartition("/")

        folder_depth = folder_part.count("/") + 1 if folder_part else 0

        if folder_depth > self.constraints.max_folder_depth:
            raise PathConstraintError(
                f"Generated path exceeds max folder depth of {self.constraints.max_folder_depth}: "
                f"{folder_depth} levels"
            )

        if folder_part:
            allowed_chars = self.constraints.allowed_chars
            pattern = f"^[{allowed_chars}]+$"
            for segment in folder_part.split("/"):
                if not re.match(pattern, segment):
                    raise PathConstraintError(
                        f"Folder segment '{segment}' contains disallowed characters "
                        f"(allowed: [{allowed_chars}])"
                    )


def build_suggested_path(
    classification: RawClassification,
    original_path: Path,
    naming_policy: BaseNamingPolicy,
    constraints: PathConstraints | None = None,
    taxonomy: BaseTaxonomy | None = None,
    emit_entity: bool = True,
    redact_entity_in_domains: list[str] | None = None,
) -> ClassificationResult:
    """Convenience function to build a suggested path.

    Args:
        classification: Normalized classification from LLM.
        original_path: Original document file path.
        naming_policy: Naming policy for filename generation.
        constraints: Path constraints, or None for defaults.
        taxonomy: Optional taxonomy for singular-form filename generation.
        emit_entity: When False, suppress the entity slot for every document.
        redact_entity_in_domains: Domains whose entity slot is suppressed
            for privacy. Defaults to ``["medical"]``.

    Returns:
        ClassificationResult with suggested path.
    """
    builder = PathBuilder(
        naming_policy=naming_policy,
        constraints=constraints,
        taxonomy=taxonomy,
        emit_entity=emit_entity,
        redact_entity_in_domains=redact_entity_in_domains,
    )
    return builder.build(classification, original_path)
