"""Path builder for generating organized file paths from classification.

Constructs paths following the format:
{domain}/{category}/{doctype}/{filename}

Where filename is generated by the naming policy.
"""

import re
from pathlib import Path

from drover.models import ClassificationResult, PathConstraints, RawClassification
from drover.naming.base import BaseNamingPolicy


class PathConstraintError(Exception):
    """Raised when a generated path or filename violates constraints."""


class PathBuilder:
    """Builds file paths from classification results.

    Combines folder structure with naming policy to generate
    complete, policy-compliant file paths.
    """

    def __init__(
        self,
        naming_policy: BaseNamingPolicy,
        constraints: PathConstraints | None = None,
    ) -> None:
        """Initialize path builder.

        Args:
            naming_policy: Policy for generating filenames.
            constraints: Path constraints, or None for defaults.
        """
        self.naming_policy = naming_policy
        self.constraints = constraints or PathConstraints()

    def build(
        self,
        classification: RawClassification,
        original_path: Path,
    ) -> ClassificationResult:
        """Build complete classification result with suggested path.

        Args:
            classification: Normalized classification from LLM.
            original_path: Original document file path.

        Returns:
            ClassificationResult with suggested path.
        """
        folder_path = self._build_folder_path(
            domain=classification.domain,
            category=classification.category,
            doctype=classification.doctype,
        )

        filename = self.naming_policy.format_filename(
            doctype=classification.doctype,
            vendor=classification.vendor,
            subject=classification.subject,
            date=classification.date,
            extension=original_path.suffix,
        )

        is_valid, error_message = self.naming_policy.validate_filename(filename)
        if not is_valid:
            raise PathConstraintError(
                error_message or "Generated filename violates naming constraints"
            )

        suggested_path = f"{folder_path}/{filename}"
        self._validate_path(suggested_path)

        return ClassificationResult(
            original=original_path.name,
            suggested_path=suggested_path,
            suggested_filename=filename,
            domain=classification.domain,
            category=classification.category,
            doctype=classification.doctype,
            vendor=classification.vendor,
            date=classification.date,
            subject=classification.subject,
        )

    def _build_folder_path(
        self,
        domain: str,
        category: str,
        doctype: str,
    ) -> str:
        """Build folder path from classification components.

        Args:
            domain: Canonical domain.
            category: Canonical category.
            doctype: Canonical document type.

        Returns:
            Folder path string (without trailing slash).
        """
        parts = [domain, category, doctype]

        if len(parts) > self.constraints.max_folder_depth:
            parts = parts[: self.constraints.max_folder_depth]

        return "/".join(parts)

    def _validate_path(self, path: str) -> None:
        """Validate path against constraints.

        Args:
            path: Full suggested path.

        Raises:
            PathConstraintError: If path violates constraints.
        """
        if len(path) > self.constraints.max_path_length:
            raise PathConstraintError(
                f"Generated path exceeds max length of {self.constraints.max_path_length}: "
                f"{len(path)} chars"
            )

        folder_part, _, _ = path.rpartition("/")

        if folder_part:
            folder_depth = folder_part.count("/") + 1
        else:
            folder_depth = 0

        if folder_depth > self.constraints.max_folder_depth:
            raise PathConstraintError(
                f"Generated path exceeds max folder depth of {self.constraints.max_folder_depth}: "
                f"{folder_depth} levels"
            )

        if folder_part:
            allowed_chars = self.constraints.allowed_chars
            pattern = f"^[{allowed_chars}]+$"
            for segment in folder_part.split("/"):
                if not re.match(pattern, segment):
                    raise PathConstraintError(
                        f"Folder segment '{segment}' contains disallowed characters "
                        f"(allowed: [{allowed_chars}])"
                    )


def build_suggested_path(
    classification: RawClassification,
    original_path: Path,
    naming_policy: BaseNamingPolicy,
    constraints: PathConstraints | None = None,
) -> ClassificationResult:
    """Convenience function to build a suggested path.

    Args:
        classification: Normalized classification from LLM.
        original_path: Original document file path.
        naming_policy: Naming policy for filename generation.
        constraints: Path constraints, or None for defaults.

    Returns:
        ClassificationResult with suggested path.
    """
    builder = PathBuilder(naming_policy=naming_policy, constraints=constraints)
    return builder.build(classification, original_path)
