"""Path builder for generating organized file paths from classification.

Constructs paths following the format:
{domain}/{category}/{doctype}/{filename}

Where filename is generated by the naming policy.
"""

from pathlib import Path

from drover.models import ClassificationResult, PathConstraints, RawClassification
from drover.naming.base import BaseNamingPolicy


class PathBuilder:
    """Builds file paths from classification results.

    Combines folder structure with naming policy to generate
    complete, policy-compliant file paths.
    """

    def __init__(
        self,
        naming_policy: BaseNamingPolicy,
        constraints: PathConstraints | None = None,
    ) -> None:
        """Initialize path builder.

        Args:
            naming_policy: Policy for generating filenames.
            constraints: Path constraints, or None for defaults.
        """
        self.naming_policy = naming_policy
        self.constraints = constraints or PathConstraints()

    def build(
        self,
        classification: RawClassification,
        original_path: Path,
    ) -> ClassificationResult:
        """Build complete classification result with suggested path.

        Args:
            classification: Normalized classification from LLM.
            original_path: Original document file path.

        Returns:
            ClassificationResult with suggested path.
        """
        # Build folder structure
        folder_path = self._build_folder_path(
            domain=classification.domain,
            category=classification.category,
            doctype=classification.doctype,
        )

        # Generate filename
        filename = self.naming_policy.format_filename(
            doctype=classification.doctype,
            vendor=classification.vendor,
            subject=classification.subject,
            date=classification.date,
            extension=original_path.suffix,
        )

        # Combine into full path
        suggested_path = f"{folder_path}/{filename}"

        # Validate constraints
        self._validate_path(suggested_path)

        return ClassificationResult(
            original=original_path.name,
            suggested_path=suggested_path,
            domain=classification.domain,
            category=classification.category,
            doctype=classification.doctype,
            vendor=classification.vendor,
            date=classification.date,
            subject=classification.subject,
        )

    def _build_folder_path(
        self,
        domain: str,
        category: str,
        doctype: str,
    ) -> str:
        """Build folder path from classification components.

        Args:
            domain: Canonical domain.
            category: Canonical category.
            doctype: Canonical document type.

        Returns:
            Folder path string (without trailing slash).
        """
        parts = [domain, category, doctype]

        # Check folder depth constraint
        if len(parts) > self.constraints.max_folder_depth:
            # Flatten by removing middle components
            parts = parts[: self.constraints.max_folder_depth]

        return "/".join(parts)

    def _validate_path(self, path: str) -> None:
        """Validate path against constraints.

        Args:
            path: Full suggested path.

        Raises:
            ValueError: If path violates constraints.
        """
        if len(path) > self.constraints.max_path_length:
            raise ValueError(
                f"Generated path exceeds max length of {self.constraints.max_path_length}: "
                f"{len(path)} chars"
            )

        # Count folder depth
        folder_depth = path.count("/")
        if folder_depth > self.constraints.max_folder_depth:
            raise ValueError(
                f"Generated path exceeds max folder depth of {self.constraints.max_folder_depth}: "
                f"{folder_depth} levels"
            )


def build_suggested_path(
    classification: RawClassification,
    original_path: Path,
    naming_policy: BaseNamingPolicy,
    constraints: PathConstraints | None = None,
) -> ClassificationResult:
    """Convenience function to build a suggested path.

    Args:
        classification: Normalized classification from LLM.
        original_path: Original document file path.
        naming_policy: Naming policy for filename generation.
        constraints: Path constraints, or None for defaults.

    Returns:
        ClassificationResult with suggested path.
    """
    builder = PathBuilder(naming_policy=naming_policy, constraints=constraints)
    return builder.build(classification, original_path)
